import os

def finalize_database_namuwiki_style():
    base_path = r'c:\Users\Admin\Desktop\게임기획\포트폴리오\게임-기획자-포트폴리오-개선버전'
    
    # [나무위키 기준 회사명 번역 사전]
    C_MAP = {
        "Valve": "밸브 코퍼레이션",
        "Riot Games": "라이엇 게임즈",
        "Blizzard": "블리자드 엔터테인먼트",
        "Nintendo": "닌텐도",
        "Supercell": "슈퍼셀",
        "Nexon": "넥슨",
        "Nexon Games": "넥슨게임즈",
        "Nexon GT": "넥슨지티",
        "Smilegate RPG": "스마일게이트 RPG",
        "KRAFTON": "크래프톤",
        "Pearl Abyss": "펄어비스",
        "FromSoftware": "프롬 소프트웨어",
        "Ubisoft": "유비소프트",
        "Capcom": "캡콤",
        "Rockstar Games": "락스타 게임즈",
        "Square Enix": "스퀘어 에닉스",
        "Sega": "세가",
        "Cygames": "사이게임즈",
        "HoYoverse": "호요버스",
        "NetEase Games": "넷이즈 게임즈",
        "NetEase": "넷이즈",
        "Embark Studios": "엠바크 스튜디오",
        "EA Sports": "EA 스포츠",
        "EA Sports/Nexon": "EA 스포츠 / 넥슨",
        "Shift Up": "시프트업",
        "Innersloth": "이너슬로스",
        "Devsisters": "데브시스터즈",
        "Hypergryph": "하이퍼그리프",
        "Kuro Games": "쿠로 게임즈",
        "Netmarble": "넷마블",
        "NCSoft": "엔씨소프트",
        "Neowiz": "네오위즈",
        "Com2uS": "컴투스",
        "Gamevil": "게임빌",
        "Mgame": "엠게임",
        "KOG": "KOG",
        "Project Moon": "프로젝트 문",
        "Nimble Neuron": "님블뉴런",
        "Pearl Abyss": "펄어비스",
        "Bandai Namco": "반다이 남코",
        "Konami": "코나미",
        "Hazelight Studios": "헤이즐라이트 스튜디오",
        "Larian Studios": "라리안 스튜디오",
        "CD Projekt Red": "CD 프로젝트 레드",
        "Warhorse Studios": "워호스 스튜디오",
        "Team Cherry": "팀 체리",
        "MegaCrit": "메가크리트",
        "poncle": "폰클",
        "Askiisoft": "아스키소프트",
        "Gaggle Studios": "개글 스튜디오",
        "Coffee Stain Studios": "커피 스테인 스튜디오",
        "Robot Gentleman": "로봇 젠틀맨",
        "Ndemic Creations": "엔데믹 크리에이션즈",
        "PopCap Games": "팝캡 게임즈",
        "Taito": "타이토",
        "Toaplan": "토아플랜",
        "Hudson Soft": "허드슨 소프트",
        "Irem": "아이렘",
        "SNK": "SNK",
        "Data East": "데이터 이스트",
        "Seibu Kaihatsu": "세이부 개발",
        "Irem": "아이렘",
        "Unknown Developer": "개발사 미상",
        "Various": "다수"
    }

    # [한국어 장르 번역 사전 (최적화 버전)]
    G_MAP = {
        "Tactical FPS": "전술 FPS", "MOBA Shooter": "AOS 슈팅", "Sports (Football)": "스포츠(축구)",
        "Battle Royale": "배틀로얄", "Hero Shooter": "히어로 슈팅", "Rhythm/Action": "리듬 액션",
        "Hack and Slash MMORPG": "핵앤슬래시 MMORPG", "MMORPG": "MMORPG", "Action RPG": "액션 RPG",
        "Belt-scrolling Action RPG": "벨트스크롤 액션", "Metaverse Platform": "메타버스",
        "2D Side-scrolling MMORPG": "2D 횡스크롤 MMORPG", "Platform": "플랫폼", "RTS": "RTS",
        "Turn-based Artillery": "턴제 포격", "FPS": "FPS", "Kart Racing": "카트 레이싱",
        "Casual Puzzle": "캐주얼 퍼즐", "TPS": "TPS", "Action": "액션", "Racing": "레이싱",
        "MOBA": "AOS", "Action MOBA": "액션 AOS", "CCG": "CCG", "Sports": "스포츠",
        "Real-time Action Combat": "실시간 액션", "Narrative CCG": "스토리 CCG",
        "Tower Defense RPG": "타워디펜스 RPG", "Survival Crafting": "생존 제작",
        "Location-based AR": "위치기반 AR", "Sleep Tracking Game": "수면 기록",
        "Tactical Subculture RPG": "전략 서브컬처", "Open World Action RPG": "오픈월드 액션",
        "Tower Defense": "타워 디펜스", "Strategy RPG": "전략 RPG", "Social Deduction": "소셜 디덕션",
        "Strategy Simulation": "전략 시뮬레이션", "Real-time Strategy Card": "전략 카드",
        "Combat Strategy": "전투 전략", "AFK RPG": "방치형 RPG", "Idle RPG": "방치형 RPG",
        "Turn-based RPG": "턴제 RPG", "Endless Runner": "런게임", "Puzzle": "퍼즐",
        "Roguelike RPG": "로그라이크 RPG", "Action Roguelike": "액션 로그라이크",
        "Visual Novel": "비주얼 노벨", "Open World Action RPG (Soulslike)": "오픈월드 소울라이크",
        "Adventure": "어드벤처", "First-person Open World RPG": "1인칭 오픈월드",
        "Wuxia Management RPG": "무협 경영 RPG", "Metroidvania": "메트로배니아",
        "Roguelike Deck-builder": "로그라이크 덱빌딩", "Roguelite Bullet Heaven": "로그라이트 슈팅",
        "First-person Puzzle": "1인칭 퍼즐", "Co-op Zombie Shooter": "협동 좀비 슈팅",
        "Platformer Arcade": "플랫폼 아케이드", "2D Grappling Action": "2D 와이어 액션",
        "Dystopian Document Thriller": "디스토피아 추리", "Indie RPG": "인디 RPG",
        "Action Platformer": "액션 플랫폼", "Survival Simulation": "생존 시뮬레이션",
        "Co-op Adventure": "협동 어드벤처", "RPG": "RPG", "Looter Shooter": "루터 슈팅",
        "Open World RPG": "오픈월드 RPG", "Fighting": "격투", "Rhythm": "리듬",
        "Survival RPG": "생존 RPG", "Co-op Horror": "협동 공포", "Tactical Shooter": "전술 슈팅",
        "Open World Western Adventure": "오픈월드 서부", "4X Strategy": "4X 전략",
        "Sandbox Survival": "샌드박스 생존", "Survival Horror": "생존 공포",
        "Beat 'em up": "벨트스크롤 액션", "Bullet Hell": "탄막 슈팅", "Mobile Action": "모바일 액션",
        "Roguelike Survival": "로그라이크 생존", "Runner": "런게임", "Social Puzzle": "소셜 퍼즐",
        "Defense": "디펜스", "Action Adventure": "액션 어드벤처"
    }

    # [데이터 리스트]
    # (PC - 72)
    PC_LIST = [
        ("ARC Raiders", "Embark Studios", "Tactical FPS"), ("Counter-Strike: Global Offensive", "Valve", "Tactical FPS"),
        ("Deadlock", "Valve", "MOBA Shooter"), ("FC온라인", "EA Sports/Nexon", "Sports (Football)"),
        ("PUBG: 배틀그라운드", "KRAFTON", "Battle Royale"), ("Team Fortress 2", "Valve", "Hero Shooter"),
        ("osu!", "ppy", "Rhythm/Action"), ("검은사막", "Pearl Abyss", "Hack and Slash MMORPG"),
        ("귀혼", "Mgame", "MMORPG"), ("그랜드체이스", "KOG", "Action RPG"),
        ("던전앤파이터", "Nexon", "Belt-scrolling Action RPG"), ("로블록스", "Roblox Corporation", "Metaverse Platform"),
        ("로스트아크", "Smilegate RPG", "Hack and Slash MMORPG"), ("리그 오브 레전드", "Riot Games", "MOBA"),
        ("마블 라이벌즈", "NetEase Games", "Hero Shooter"), ("메이플스토리", "Nexon", "2D Side-scrolling MMORPG"),
        ("메이플스토리 월드", "Nexon", "Platform"), ("발로란트", "Riot Games", "Tactical FPS"),
        ("에버플래닛", "Nexon", "MMORPG"), ("이터널 리턴", "Nimble Neuron", "Battle Royale"),
        ("스타크래프트 2", "Blizzard", "RTS"), ("오버워치", "Blizzard", "Hero Shooter"),
        ("포트리스 2", "CCR", "Turn-based Artillery"), ("바람의나라", "Nexon", "MMORPG"),
        ("서든어택", "Nexon GT", "FPS"), ("카트라이더: 드리프트", "Nexon", "Kart Racing"),
        ("크레이지아케이드", "Nexon", "Casual Puzzle"), ("테일즈위버", "Nexon", "MMORPG"),
        ("클로저스", "Nadic Games", "Action RPG"), ("워크래프트 3", "Blizzard", "RTS"),
        ("배틀라이트", "Stunlock Studios", "MOBA"), ("버블슈터", "Various", "Casual Puzzle"),
        ("버블파이터", "Nexon", "TPS"), ("봄버맨 온라인", "Hudson Soft", "Action"),
        ("뿌까 퍼니레이스", "Various", "Racing"), ("서머너즈 워: 크로니클", "Com2uS", "MMORPG"),
        ("서유기전 온라인", "Mgame", "MMORPG"), ("슈퍼바이브", "Theorycraft Games", "MOBA Shooter"),
        ("스타크래프트", "Blizzard", "RTS"), ("얍카", "Various", "Action RPG"),
        ("에어라이더", "Nexon", "Racing"), ("엑스틸", "NCSoft", "Action"),
        ("엘소드", "KOG", "Action RPG"), ("열혈강호", "Mgame", "MMORPG"),
        ("우뿌", "Various", "Action"), ("워헤이븐", "Nexon", "Action"),
        ("웜즈 온라인", "Team17", "Turn-based Strategy"), ("윈드슬레이어", "Various", "MMORPG"),
        ("전략적 팀 전투", "Riot Games", "Auto Battler"), ("커츠펠", "KOG", "Action RPG"),
        ("케로로파이터", "Various", "Action"), ("쿵야 어드벤처", "Netmarble", "MMORPG"),
        ("큐플레이", "Nexon", "Social Puzzle"), ("크레이지레이싱 카트라이더", "Nexon", "Racing"),
        ("톰 클랜시의 레인보우 식스 시즈", "Ubisoft", "Tactical FPS"), ("패스 오브 엑자일 2", "Grinding Gear Games", "Action RPG"),
        ("프리프", "Gala Lab", "MMORPG"), ("피구왕 마시마로", "Various", "Sports"),
        ("하스스톤", "Blizzard", "CCG"), ("하이퍼유니버스", "Cwiggl", "Action MOBA"),
        ("히어로즈 오브 더 스톰", "Blizzard", "MOBA"), ("마법학교 아르피아", "NCSoft", "RPG"),
        ("마법학교 아스티넬", "NCSoft", "RPG"), ("믹스마스터", "Various", "MMORPG"),
        ("바우트", "Various", "Action"), ("아크 레이더스", "Embark Studios", "Co-op Shooter"),
        ("라테일", "HappyTuk", "MMORPG"), ("디지몬 RPG", "MoveGames", "MMORPG"),
        ("디지몬 온라인", "Bandai", "MMORPG"), ("로스트사가", "Valofe", "Action"),
        ("검은사막", "Pearl Abyss", "MMORPG"), ("FC온라인", "EA Sports", "Sports")
    ]

    # MOBILE (115)
    MOBILE_LIST = [
        ("브롤스타즈", "Supercell", "Real-time Action Combat"), ("데스티니 차일드", "Shift Up", "Narrative CCG"),
        ("무기미도", "AISNO Games", "Tower Defense RPG"), ("지구의 마지막 날: 생존", "Kefir!", "Survival Crafting"),
        ("Pokémon GO", "Niantic/Nintendo", "Location-based AR"), ("Pokémon Sleep", "The Pokémon Company", "Sleep Tracking Game"),
        ("Pokémon Masters EX", "The Pokémon Company", "Turn-based RPG"), ("Pokémon Duel", "The Pokémon Company", "Strategy Board Game"),
        ("스타세이비어", "Unknown Developer", "Mobile Action"), ("블루아카이브", "Nexon Games", "Tactical Subculture RPG"),
        ("원신", "HoYoverse", "Open World Action RPG"), ("명일방주", "Hypergryph", "Tower Defense"),
        ("쿠키런: 킹덤", "Devsisters", "Strategy RPG"), ("어몽 어스", "Innersloth", "Social Deduction"),
        ("전염병 주식회사", "Ndemic Creations", "Strategy Simulation"), ("클래시 로얄", "Supercell", "Real-time Strategy Card"),
        ("클래시 오브 클랜", "Supercell", "Combat Strategy"), ("AFK 아레나", "Lilith Games", "AFK RPG"),
        ("림버스 컴퍼니", "Project Moon", "Turn-based RPG"), ("2010 프로야구", "Gamevil", "Sports"),
        ("2011 프로야구", "Gamevil", "Sports"), ("2012 프로야구", "Gamevil", "Sports"),
        ("2013 프로야구", "Gamevil", "Sports"), ("붐비치", "Supercell", "Strategy"),
        ("스쿼드 버스터즈", "Supercell", "Action"), ("서브웨이 서퍼", "Kiloo", "Endless Runner"),
        ("템플 런", "Imangi Studios", "Endless Runner"), ("후르츠 닌자", "Halfbrick Studios", "Action"),
        ("V4", "Nexon", "MMORPG"), ("블록쿠도쿠: 블록 퍼즐 게임", "Easybrain", "Puzzle"),
        ("Buriedbornes", "Nussygame", "Roguelike RPG"), ("王者荣耀(왕자영요)", "Tencent", "MOBA"),
        ("가디언 테일즈", "Kong Studios", "Action RPG"), ("갓깨비 키우기", "Various", "Idle RPG"),
        ("겨울의 탑", "Various", "Adventure"), ("궁수의 전설", "Habby", "Action Roguelike"),
        ("궁수의 전설 2", "Habby", "Action Roguelike"), ("그루브 코스터 2", "Taito", "Rhythm"),
        ("길건너친구들", "Hipster Whale", "Arcade"), ("깨어난 마녀", "Yostar", "RPG"),
        ("꿈의 정원", "Playrix", "Puzzle"), ("꿈의 집", "Playrix", "Puzzle"),
        ("달토끼 키우기", "Various", "Idle RPG"), ("드래곤플라이트", "NextFloor", "Shooting"),
        ("디지몬 링크즈", "Bandai Namco", "RPG"), ("랜덤 다이스: 디펜스", "111%", "Tower Defense"),
        ("레전드 오브 슬라임: 방치형 RPG", "LoadComplete", "Idle RPG"), ("로블록스", "Roblox Corporation", "Sandbox"),
        ("로스트 소드", "Various", "RPG"), ("리듬스타", "A&B Soft", "Rhythm"),
        ("마피아42", "TEAM42", "Social Deduction"), ("매직서바이벌", "lemo", "Roguelike Survival"),
        ("메이플스토리 LIVE", "Nexon", "Action RPG"), ("메이플스토리 M", "Nexon", "MMORPG"),
        ("메이플스토리 도적편", "Nexon", "Action RPG"), ("메이플스토리 시그너스기사단", "Nexon", "Action RPG"),
        ("메이플스토리 핸디월드", "Nexon", "Platform"), ("명일방주: 엔드필드", "Hypergryph", "Open World RPG"),
        ("명조: 워더링 웨이브", "Kuro Games", "Open World Action RPG"), ("모두의 마블", "Netmarble", "Board Game"),
        ("바람의나라: 연", "Nexon", "MMORPG"), ("바운스볼", "Various", "Puzzle"),
        ("뱅드림! 걸즈 밴드 파티!", "Craft Egg", "Rhythm"), ("별이 되어라2", "FLINT", "Action RPG"),
        ("브라운더스트", "Neowiz", "Strategy RPG"), ("브라운더스트 2", "Neowiz", "Strategy RPG"),
        ("블랙서바이벌", "Nimble Neuron", "Survival"), ("삼국지 책략전", "Various", "Strategy"),
        ("삼국지 천하포무", "Various", "Strategy"), ("서울 2033", "Banjiha Games", "Text Adventure"),
        ("세븐 데이즈", "Buff Studio", "Visual Novel"), ("소녀전선", "Mica Team", "Strategy RPG"),
        ("소녀전선 2: 망명", "Mica Team", "Strategy RPG"), ("소드마스터 스토리", "SuperPlanet", "Action RPG"),
        ("슈퍼액션히어로3", "Com2uS", "Action"), ("스노우레인1", "Various", "Visual Novel"),
        ("스노우레인2", "Various", "Visual Novel"), ("스매시 레전드", "5minlab", "Action"),
        ("신선놀음 이모탈", "Various", "Idle RPG"), ("아스팔트6", "Gameloft", "Racing"),
        ("아이돌마스터 신데렐라 걸즈 스타라이트 스테이지", "Cygames", "Rhythm"), ("언더월드 오피스", "Buff Studio", "Visual Novel"),
        ("얼터 에고", "Caramel Column", "Adventure"), ("얼티밋 스쿨", "NetEase", "MOBA"),
        ("우마무스메 프리티 더비", "Cygames", "Simulation"), ("원펀맨: 최강의 남자", "Various", "RPG"),
        ("유희왕 듀얼링크스", "Konami", "CCG"), ("유희왕 마스터듀얼", "Konami", "CCG"),
        ("이노티아 4", "Com2uS", "RPG"), ("제노니아 3", "Gamevil", "RPG"),
        ("제노니아 4", "Gamevil", "RPG"), ("제노니아 5", "Gamevil", "RPG"),
        ("젠레스 존 제로", "HoYoverse", "Action RPG"), ("중고로운 평화나라", "Various", "Simulation"),
        ("카미츠바키시 협주중.", "Various", "Rhythm"), ("카오스앤디펜스", "Various", "Strategy"),
        ("카운터사이드", "Studiobside", "Strategy RPG"), ("카툰워즈 2", "Gamevil", "Defense"),
        ("카트라이더 러쉬플러스", "Nexon", "Racing"), ("캔디 크러쉬 사가", "King", "Puzzle"),
        ("쿠키런: 오븐브레이크", "Devsisters", "Runner"), ("쿵야 캐치마인드", "Netmarble", "Social Puzzle"),
        ("크루세이더 퀘스트", "LoadComplete", "Action RPG"), ("팔라독", "Fazecat", "Defense"),
        ("포켓몬 카드 게임 Pocket", "Creatures", "CCG"), ("프로젝트 세카이 컬러풀 스테이지! feat. 하츠네 미쿠", "Sega", "Rhythm"),
        ("프린세스 커넥트! Re:Dive", "Cygames", "RPG"), ("할아버지와 요람", "Various", "Adventure"),
        ("허언증 소개팅", "Various", "Simulation"), ("호연", "NCSoft", "RPG"),
        ("히트2", "Nexon", "MMORPG")
    ]

    # CONSOLE/STEAM (174)
    CONSOLE_LIST = [
        ("Among Us", "Innersloth", "Social Deduction"), ("엘든 링", "FromSoftware", "Open World Action RPG (Soulslike)"),
        ("Look Outside", "Unknown Developer", "Adventure"), ("Kingdom Come: Deliverance II", "Warhorse Studios", "First-person Open World RPG"),
        ("활협전", "Obis Loop", "Wuxia Management RPG"), ("Plants vs. Zombies", "PopCap Games", "Tower Defense"),
        ("Hollow Knight", "Team Cherry", "Metroidvania"), ("Slay the Spire", "MegaCrit", "Roguelike Deck-builder"),
        ("Vampire Survivors", "poncle", "Roguelite Bullet Heaven"), ("Portal 2", "Valve", "First-person Puzzle"),
        ("Left 4 Dead 2", "Valve", "Co-op Zombie Shooter"), ("스노우브라더스", "Toaplan", "Platformer Arcade"),
        ("산나비", "Wonder Potion", "2D Grappling Action"), ("Papers, Please", "3909", "Dystopian Document Thriller"),
        ("Undertale", "Toby Fox", "Indie RPG"), ("Katana ZERO", "Askiisoft", "Action Platformer"),
        ("Goose Goose Duck", "Gaggle Studios", "Social Deduction"), ("Goat Simulator", "Coffee Stain Studios", "Simulation"),
        ("60 Seconds!", "Robot Gentleman", "Survival Simulation"), ("7 Days to End with You", "Various", "Adventure"),
        ("A Way Out", "Hazelight Studios", "Co-op Adventure"), ("Baldur's Gate 3", "Larian Studios", "RPG"),
        ("Blasphemous", "The Game Kitchen", "Metroidvania"), ("Borderlands 2", "Gearbox Software", "Looter Shooter"),
        ("Borderlands 3", "Gearbox Software", "Looter Shooter"), ("Cyberpunk 2077", "CD Projekt Red", "Open World RPG"),
        ("DNF 듀얼", "Arc System Works/Nexon", "Fighting"), ("DARK SOULS II", "FromSoftware", "Action RPG"),
        ("DARK SOULS III", "FromSoftware", "Action RPG"), ("DARK SOULS: REMASTERED", "FromSoftware", "Action RPG"),
        ("DJMAX RESPECT V", "NEOWIZ", "Rhythm"), ("Danganronpa 2: Goodbye Despair", "Spike Chunsoft", "Visual Novel"),
        ("Danganronpa V3: Killing Harmony", "Spike Chunsoft", "Visual Novel"), ("Danganronpa: Trigger Happy Havoc", "Spike Chunsoft", "Visual Novel"),
        ("Enshrouded", "Keen Games", "Survival RPG"), ("Fakebook", "Various", "Simulation"),
        ("For Honor", "Ubisoft", "Action"), ("Frostpunk", "11 bit studios", "Survival Management"),
        ("GTA V", "Rockstar Games", "Open World Action"), ("GTA: Chinatown Wars", "Rockstar Games", "Open World Action"),
        ("GTA: San Andreas", "Rockstar Games", "Open World Action"), ("Ghost Trick", "Capcom", "Puzzle Adventure"),
        ("Helldivers 2", "Arrowhead Game Studios", "Co-op Shooter"), ("Ib", "kouri", "Horror Adventure"),
        ("Inscryption", "Daniel Mullins Games", "Roguelike Deck-builder"), ("Legal Dungeon", "Somi", "Simulation"),
        ("Lethal Company", "Zeekerss", "Co-op Horror"), ("Muse Dash", "PeroPeroGames", "Rhythm"),
        ("Nidhogg", "Messhof", "Action"), ("OMORI", "OMOCAT", "RPG"),
        ("PAYDAY 2", "Overkill Software", "Co-op Heist Shooter"), ("Palworld", "Pocketpair", "Survival Crafting"),
        ("P의 거짓", "NEOWIZ", "Action RPG (Soulslike)"), ("RUNNING WITH RIFLES", "Osumia Games", "Tactical Shooter"),
        ("Ready Action", "Various", "Action"), ("Red Dead Redemption 2", "Rockstar Games", "Open World Western Adventure"),
        ("Refind Self: 성격 진단 게임", "Various", "Adventure"), ("Rust", "Facepunch Studios", "Survival"),
        ("SEKIRO: SHADOWS DIE TWICE", "FromSoftware", "Action Adventure"), ("Sid Meier's Civilization V", "Firaxis Games", "4X Strategy"),
        ("Slay the Spire 2", "MegaCrit", "Roguelike Deck-builder"), ("Snow Bros. 2: With New Elves", "Toaplan", "Platformer Arcade"),
        ("Spiral Knights", "Grey Havens", "Action RPG"), ("Terraria", "Re-Logic", "Sandbox Survival"),
        ("The Forest", "Endnight Games", "Survival Horror"), ("The Sims 4 Get to Work", "Maxis", "Life Simulation"),
        ("This War of Mine", "11 bit studios", "Survival"), ("Unsouled", "Me we", "Action RPG"),
        ("Untitled Goose Game", "House House", "Puzzle"), ("V Rising", "Stunlock Studios", "Action Survival"),
        ("가정교사 히트맨 REBORN! DS 플레임 럼블 XX 초결전! 리얼 6조화", "Takara Tomy", "Fighting"), ("귀곡팔황", "Various", "Open World RPG"),
        ("기적의 분식집", "TalesShop", "Visual Novel"), ("나루토 최강닌자 대결집 DS", "Tomy", "Action"),
        ("놀러오세요 동물의 숲", "Nintendo", "Life Simulation"), ("뉴 슈퍼 마리오브라더스", "Nintendo", "Platformer"),
        ("닌자베이스볼배트맨", "Irem", "Beat 'em up"), ("대역전재판 -나루호도 류노스케의 모험-", "Capcom", "Visual Novel"),
        ("대역전재판2 -나루호도 류노스케의 각오-", "Capcom", "Visual Novel"), ("더 킹 오브 파이터즈 XV", "SNK", "Fighting"),
        ("도와줘! 리듬 히어로", "Nintendo", "Rhythm"), ("동방비상천 ~ Scarlet Weather Rhapsody.", "Twilight Frontier", "Fighting"),
        ("동방비상천칙 ~ 초대형 기뇰의 수수께끼를 쫓아서", "Twilight Frontier", "Fighting"), ("동방영야초 ~ Imperishable Night.", "Team Shanghai Alice", "Bullet Hell"),
        ("동방요요몽 ~ Perfect Cherry Blossom.", "Team Shanghai Alice", "Bullet Hell"), ("동방췌몽상 ~ Immaterial and Missing Power.", "Twilight Frontier", "Fighting"),
        ("동방홍룡동 ~ Unconnected Marketeers.", "Team Shanghai Alice", "Bullet Hell"), ("동방홍마향 ~ the Embodiment of Scarlet Devil.", "Team Shanghai Alice", "Bullet Hell"),
        ("드래곤 퀘스트 V 천공의 신부", "Square Enix", "RPG"), ("디지몬 챔피언십", "Bandai Namco", "Simulation"),
        ("라그나로크 DS", "GungHo", "RPG"), ("라이덴 2", "Seibu Kaihatsu", "Shooting"),
        ("라이프 이즈 퓨달: MMO", "Bitbox Ltd.", "MMORPG"), ("레이튼 교수와 이상한 마을", "Level-5", "Puzzle Adventure"),
        ("렐름 오브 더 매드 갓", "Deca Games", "Bullet Hell MMO"), ("록맨 X", "Capcom", "Action Platformer"),
        ("리듬 세상", "Nintendo", "Rhythm"), ("말랑말랑 두뇌교실", "Nintendo", "Puzzle"),
        ("메이드 인 와리오", "Nintendo", "Action"), ("메타포: 리판타지오", "Atlus", "RPG"),
        ("메탈슬러그", "SNK", "Run and Gun"), ("메탈슬러그 2", "SNK", "Run and Gun"),
        ("메탈슬러그 3", "SNK", "Run and Gun"), ("메탈슬러그 4", "SNK", "Run and Gun"),
        ("메탈슬러그 7", "SNK", "Run and Gun"), ("몬스터 헌터: 월드", "Capcom", "Action RPG"),
        ("미라클 어드벤처", "Data East", "Action"), ("별의 커비 도팡 일당의 습격", "Nintendo", "Platformer"),
        ("별의 커비 울트라 슈퍼 디럭스", "Nintendo", "Platformer"), ("삼국지 11", "Koei Tecmo", "Strategy"),
        ("삼국지 12", "Koei Tecmo", "Strategy"), ("삼국지 13", "Koei Tecmo", "Strategy"),
        ("삼국지 14", "Koei Tecmo", "Strategy"), ("삼국지 7", "Koei Tecmo", "Strategy"),
        ("삼국지 8", "Koei Tecmo", "Strategy"), ("삼국지 8 리메이크", "Koei Tecmo", "Strategy"),
        ("세피리아", "Various", "RPG"), ("섹시 파로디우스", "Konami", "Shooting"),
        ("슈퍼 마리오 64", "Nintendo", "Platformer"), ("슈퍼 마리오 랜드 2 6개의 금화", "Nintendo", "Platformer"),
        ("슈퍼 마리오 오디세이", "Nintendo", "Platformer"), ("슈퍼 피카 랜드", "Various", "Action"),
        ("스크리블너츠 언마스크드", "5TH Cell", "Puzzle"), ("스포어", "Maxis", "Simulation"),
        ("스폰지밥의 아틀란티스", "Various", "Action"), ("시벌리: 미디벌 워페어", "Torn Banner Studios", "Action"),
        ("썸썸편의점", "TalesShop", "Visual Novel"), ("엘더스크롤 5: 스카이림", "Bethesda", "Open World RPG"),
        ("역전검사 1", "Capcom", "Visual Novel"), ("역전재판 1", "Capcom", "Visual Novel"),
        ("역전재판 2", "Capcom", "Visual Novel"), ("역전재판 3", "Capcom", "Visual Novel"),
        ("역전재판 4", "Capcom", "Visual Novel"), ("오리와 눈먼 숲", "Moon Studios", "Metroidvania"),
        ("오리와 도깨비불", "Moon Studios", "Metroidvania"), ("오비스 루프", "Various", "Action"),
        ("유희왕 월드 챔피언십", "Konami", "CCG"), ("점프 얼티밋 스타즈", "Nintendo", "Fighting"),
        ("젤다의 전설 1", "Nintendo", "Action Adventure"), ("젤다의 전설 몽환의 모래시계", "Nintendo", "Action Adventure"),
        ("젤다의 전설 브레스 오브 더 와일드", "Nintendo", "Action Adventure"), ("젤다의 전설 스카워드 소드", "Nintendo", "Action Adventure"),
        ("젤다의 전설 시간의 오카리나", "Nintendo", "Action Adventure"), ("젤다의 전설 이상한 모자", "Nintendo", "Action Adventure"),
        ("짱구는 못말려 DS 알쏭달쏭 크레용 대작전!", "Various", "Action"), ("철권 6", "Bandai Namco", "Fighting"),
        ("철권 7", "Bandai Namco", "Fighting"), ("초강전기 키카이오", "Capcom", "Fighting"),
        ("치타맨 1", "Active Enterprises", "Action"), ("클레르 옵스큐르: 원정대 33", "Sandfall Interactive", "RPG"),
        ("킹 오브 파이터즈 98", "SNK", "Fighting"), ("킹덤컴 2", "Warhorse Studios", "RPG"),
        ("터치! 봄버맨 랜드", "Hudson Soft", "Action"), ("팀파이트 매니저", "Team Samoyed", "Simulation"),
        ("펜티먼트", "Obsidian Entertainment", "Adventure"), ("포켓몬: 야돈의 집", "The Pokémon Company", "Casual"),
        ("포켓몬스터 Y", "Nintendo", "RPG"), ("포켓몬스터 금", "Nintendo", "RPG"),
        ("포켓몬스터 기라티나", "Nintendo", "RPG"), ("포켓몬스터 디아루가", "Nintendo", "RPG"),
        ("포켓몬스터 레드", "Nintendo", "RPG"), ("포켓몬스터 문", "Nintendo", "RPG"),
        ("포켓몬스터 소드", "Nintendo", "RPG"), ("포켓몬스터 스칼렛", "Nintendo", "RPG"),
        ("포켓몬스터 알파 사파이어", "Nintendo", "RPG"), ("포켓몬스터 에메랄드", "Nintendo", "RPG"),
        ("포켓몬스터 울트라문", "Nintendo", "RPG"), ("포켓몬스터 파랑구조대", "Nintendo", "RPG"),
        ("포켓몬스터 파이어레드", "Nintendo", "RPG"), ("포켓몬스터 피카츄", "Nintendo", "RPG"),
        ("포켓몬스터 하트골드", "Nintendo", "RPG"), ("포켓몬스터 화이트", "Nintendo", "RPG"),
        ("포켓몬스터 화이트 2", "Nintendo", "RPG"), ("푸른뇌정 건볼트", "Inti Creates", "Action Platformer")
    ]

    # [파일 업데이트 실행]
    for p_name, data, disp in [("pc", PC_LIST, "Pc"), ("mobile", MOBILE_LIST, "Mobile"), ("console", CONSOLE_LIST, "Console/Steam")]:
        f_path = os.path.join(base_path, f"src/data/games/{p_name}.ts")
        content = "import type { GameHistoryItem } from '../../types';\n\n"
        content += f"export const {p_name.upper()}_GAMES: GameHistoryItem[] = [\n"
        items = []
        for i, (title, company, genre) in enumerate(data):
            # 1. 회사명 나무위키화
            kor_company = C_MAP.get(company, company)
            # 2. 장르명 한국어 최적화
            kor_genre = G_MAP.get(genre, genre)
            if "(" in kor_genre and ")" in kor_genre:
                kor_genre = kor_genre.split("(")[0].strip()
            
            items.append(f'  {{ "id": "{p_name}-{i}", "category": "{disp}", "genre": "{kor_genre}", "title": "{title}", "company": "{kor_company}" }}')
        content += ",\n".join(items) + "\n];\n"
        
        with open(f_path, 'w', encoding='utf-8') as f:
            f.write(content)

    print("Namuwiki Standard & Genre Optimization Complete.")

if __name__ == "__main__":
    finalize_database_namuwiki_style()
