import os

def restore_mobile_full():
    path = r'c:\Users\Admin\Desktop\게임기획\포트폴리오\게임-기획자-포트폴리오-개선버전\src\data\games\mobile.ts'
    
    MOBILE_GAMES_LIST = [
        ("브롤스타즈", "Supercell", "Real-time Action Combat"),
        ("데스티니 차일드", "Shift Up", "Narrative CCG"),
        ("무기미도", "AISNO Games", "Tower Defense RPG"),
        ("지구의 마지막 날: 생존", "Kefir!", "Survival Crafting"),
        ("Pokémon GO", "Niantic/Nintendo", "Location-based AR"),
        ("Pokémon Sleep", "The Pokémon Company", "Sleep Tracking Game"),
        ("Pokémon Masters EX", "The Pokémon Company", "Turn-based RPG"),
        ("Pokémon Duel", "The Pokémon Company", "Strategy Board Game"),
        ("스타세이비어", "Unknown Developer", "Mobile Action"),
        ("블루아카이브", "Nexon Games", "Tactical Subculture RPG"),
        ("원신", "HoYoverse", "Open World Action RPG"),
        ("명일방주", "Hypergryph", "Tower Defense"),
        ("쿠키런: 킹덤", "Devsisters", "Strategy RPG"),
        ("어몽 어스", "Innersloth", "Social Deduction"),
        ("전염병 주식회사", "Ndemic Creations", "Strategy Simulation"),
        ("클래시 로얄", "Supercell", "Real-time Strategy Card"),
        ("클래시 오브 클랜", "Supercell", "Combat Strategy"),
        ("AFK 아레나", "Lilith Games", "AFK RPG"),
        ("림버스 컴퍼니", "Project Moon", "Turn-based RPG"),
        ("2010 프로야구", "Gamevil", "Sports"),
        ("2011 프로야구", "Gamevil", "Sports"),
        ("2012 프로야구", "Gamevil", "Sports"),
        ("2013 프로야구", "Gamevil", "Sports"),
        ("붐비치", "Supercell", "Strategy"),
        ("스쿼드 버스터즈", "Supercell", "Action"),
        ("서브웨이 서퍼", "Kiloo", "Endless Runner"),
        ("템플 런", "Imangi Studios", "Endless Runner"),
        ("후르츠 닌자", "Halfbrick Studios", "Action"),
        ("V4", "Nexon", "MMORPG"),
        ("블록쿠도쿠: 블록 퍼즐 게임", "Easybrain", "Puzzle"),
        ("Buriedbornes", "Nussygame", "Roguelike RPG"),
        ("王者荣耀(왕자영요)", "Tencent", "MOBA"),
        ("가디언 테일즈", "Kong Studios", "Action RPG"),
        ("갓깨비 키우기", "Various", "Idle RPG"),
        ("겨울의 탑", "Various", "Adventure"),
        ("궁수의 전설", "Habby", "Action Roguelike"),
        ("궁수의 전설 2", "Habby", "Action Roguelike"),
        ("그루브 코스터 2", "Taito", "Rhythm"),
        ("길건너친구들", "Hipster Whale", "Arcade"),
        ("깨어난 마녀", "Yostar", "RPG"),
        ("꿈의 정원", "Playrix", "Puzzle"),
        ("꿈의 집", "Playrix", "Puzzle"),
        ("달토끼 키우기", "Various", "Idle RPG"),
        ("드래곤플라이트", "NextFloor", "Shooting"),
        ("디지몬 링크즈", "Bandai Namco", "RPG"),
        ("랜덤 다이스: 디펜스", "111%", "Tower Defense"),
        ("레전드 오브 슬라임: 방치형 RPG", "LoadComplete", "Idle RPG"),
        ("로블록스", "Roblox Corporation", "Sandbox"),
        ("로스트 소드", "Various", "RPG"),
        ("리듬스타", "A&B Soft", "Rhythm"),
        ("마피아42", "TEAM42", "Social Deduction"),
        ("매직서바이벌", "lemo", "Roguelike Survival"),
        ("메이플스토리 LIVE", "Nexon", "Action RPG"),
        ("메이플스토리 M", "Nexon", "MMORPG"),
        ("메이플스토리 도적편", "Nexon", "Action RPG"),
        ("메이플스토리 시그너스기사단", "Nexon", "Action RPG"),
        ("메이플스토리 핸디월드", "Nexon", "Platform"),
        ("명일방주: 엔드필드", "Hypergryph", "Open World RPG"),
        ("명조: 워더링 웨이브", "Kuro Games", "Open World Action RPG"),
        ("모두의 마블", "Netmarble", "Board Game"),
        ("바람의나라: 연", "Nexon", "MMORPG"),
        ("바운스볼", "Various", "Puzzle"),
        ("뱅드림! 걸즈 밴드 파티!", "Craft Egg", "Rhythm"),
        ("별이 되어라2", "FLINT", "Action RPG"),
        ("브라운더스트", "Neowiz", "Strategy RPG"),
        ("브라운더스트 2", "Neowiz", "Strategy RPG"),
        ("블랙서바이벌", "Nimble Neuron", "Survival"),
        ("삼국지 책략전", "Various", "Strategy"),
        ("삼국지 천하포무", "Various", "Strategy"),
        ("서울 2033", "Banjiha Games", "Text Adventure"),
        ("세븐 데이즈", "Buff Studio", "Visual Novel"),
        ("소녀전선", "Mica Team", "Strategy RPG"),
        ("소녀전선 2: 망명", "Mica Team", "Strategy RPG"),
        ("소드마스터 스토리", "SuperPlanet", "Action RPG"),
        ("슈퍼액션히어로3", "Com2uS", "Action"),
        ("스노우레인1", "Various", "Visual Novel"),
        ("스노우레인2", "Various", "Visual Novel"),
        ("스매시 레전드", "5minlab", "Action"),
        ("신선놀음 이모탈", "Various", "Idle RPG"),
        ("아스팔트6", "Gameloft", "Racing"),
        ("아이돌마스터 신데렐라 걸즈 스타라이트 스테이지", "Cygames", "Rhythm"),
        ("언더월드 오피스", "Buff Studio", "Visual Novel"),
        ("얼터 에고", "Caramel Column", "Adventure"),
        ("얼티밋 스쿨", "NetEase", "MOBA"),
        ("우마무스메 프리티 더비", "Cygames", "Simulation"),
        ("원펀맨: 최강의 남자", "Various", "RPG"),
        ("유희왕 듀얼링크스", "Konami", "CCG"),
        ("유희왕 마스터듀얼", "Konami", "CCG"),
        ("이노티아 4", "Com2uS", "RPG"),
        ("제노니아 3", "Gamevil", "RPG"),
        ("제노니아 4", "Gamevil", "RPG"),
        ("제노니아 5", "Gamevil", "RPG"),
        ("젠레스 존 제로", "HoYoverse", "Action RPG"),
        ("중고로운 평화나라", "Various", "Simulation"),
        ("카미츠바키시 협주중.", "Various", "Rhythm"),
        ("카오스앤디펜스", "Various", "Strategy"),
        ("카운터사이드", "Studiobside", "Strategy RPG"),
        ("카툰워즈 2", "Gamevil", "Defense"),
        ("카트라이더 러쉬플러스", "Nexon", "Racing"),
        ("캔디 크러쉬 사가", "King", "Puzzle"),
        ("쿠키런: 오븐브레이크", "Devsisters", "Runner"),
        ("쿵야 캐치마인드", "Netmarble", "Social Puzzle"),
        ("크루세이더 퀘스트", "LoadComplete", "Action RPG"),
        ("팔라독", "Fazecat", "Defense"),
        ("포켓몬 카드 게임 Pocket", "Creatures", "CCG"),
        ("프로젝트 세카이 컬러풀 스테이지! feat. 하츠네 미쿠", "Sega", "Rhythm"),
        ("프린세스 커넥트! Re:Dive", "Cygames", "RPG"),
        ("할아버지와 요람", "Various", "Adventure"),
        ("허언증 소개팅", "Various", "Simulation"),
        ("호연", "NCSoft", "RPG"),
        ("히트2", "Nexon", "MMORPG")
    ]

    content = "import type { GameHistoryItem } from '../../types';\n\n"
    content += "export const MOBILE_GAMES: GameHistoryItem[] = [\n"
    items = []
    for i, (title, company, genre) in enumerate(MOBILE_GAMES_LIST):
        items.append(f'  {{ "id": "mobile-{i}", "category": "Mobile", "genre": "{genre}", "title": "{title}", "company": "{company}" }}')
    content += ",\n".join(items) + "\n];\n"
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Mobile Database Restored (115 items)")

if __name__ == "__main__":
    restore_mobile_full()
