import os

def restore_console_full():
    path = r'c:\Users\Admin\Desktop\게임기획\포트폴리오\게임-기획자-포트폴리오-개선버전\src\data\games\console.ts'
    
    CONSOLE_GAMES_LIST = [
        ("Among Us", "Innersloth", "Social Deduction"),
        ("엘든 링", "FromSoftware", "Open World Action RPG (Soulslike)"),
        ("Look Outside", "Unknown Developer", "Adventure"),
        ("Kingdom Come: Deliverance II", "Warhorse Studios", "First-person Open World RPG"),
        ("활협전", "Obis Loop", "Wuxia Management RPG"),
        ("Plants vs. Zombies", "PopCap Games", "Tower Defense"),
        ("Hollow Knight", "Team Cherry", "Metroidvania"),
        ("Slay the Spire", "MegaCrit", "Roguelike Deck-builder"),
        ("Vampire Survivors", "poncle", "Roguelite Bullet Heaven"),
        ("Portal 2", "Valve", "First-person Puzzle"),
        ("Left 4 Dead 2", "Valve", "Co-op Zombie Shooter"),
        ("스노우브라더스", "Toaplan", "Platformer Arcade"),
        ("산나비", "Wonder Potion", "2D Grappling Action"),
        ("Papers, Please", "3909", "Dystopian Document Thriller"),
        ("Undertale", "Toby Fox", "Indie RPG"),
        ("Katana ZERO", "Askiisoft", "Action Platformer"),
        ("Goose Goose Duck", "Gaggle Studios", "Social Deduction"),
        ("Goat Simulator", "Coffee Stain Studios", "Simulation"),
        ("60 Seconds!", "Robot Gentleman", "Survival Simulation"),
        ("7 Days to End with You", "Various", "Adventure"),
        ("A Way Out", "Hazelight Studios", "Co-op Adventure"),
        ("Baldur's Gate 3", "Larian Studios", "RPG"),
        ("Blasphemous", "The Game Kitchen", "Metroidvania"),
        ("Borderlands 2", "Gearbox Software", "Looter Shooter"),
        ("Borderlands 3", "Gearbox Software", "Looter Shooter"),
        ("Cyberpunk 2077", "CD Projekt Red", "Open World RPG"),
        ("DNF 듀얼", "Arc System Works/Nexon", "Fighting"),
        ("DARK SOULS II", "FromSoftware", "Action RPG"),
        ("DARK SOULS III", "FromSoftware", "Action RPG"),
        ("DARK SOULS: REMASTERED", "FromSoftware", "Action RPG"),
        ("DJMAX RESPECT V", "NEOWIZ", "Rhythm"),
        ("Danganronpa 2: Goodbye Despair", "Spike Chunsoft", "Visual Novel"),
        ("Danganronpa V3: Killing Harmony", "Spike Chunsoft", "Visual Novel"),
        ("Danganronpa: Trigger Happy Havoc", "Spike Chunsoft", "Visual Novel"),
        ("Enshrouded", "Keen Games", "Survival RPG"),
        ("Fakebook", "Various", "Simulation"),
        ("For Honor", "Ubisoft", "Action"),
        ("Frostpunk", "11 bit studios", "Survival Management"),
        ("GTA V", "Rockstar Games", "Open World Action"),
        ("GTA: Chinatown Wars", "Rockstar Games", "Open World Action"),
        ("GTA: San Andreas", "Rockstar Games", "Open World Action"),
        ("Ghost Trick", "Capcom", "Puzzle Adventure"),
        ("Helldivers 2", "Arrowhead Game Studios", "Co-op Shooter"),
        ("Ib", "kouri", "Horror Adventure"),
        ("Inscryption", "Daniel Mullins Games", "Roguelike Deck-builder"),
        ("Legal Dungeon", "Somi", "Simulation"),
        ("Lethal Company", "Zeekerss", "Co-op Horror"),
        ("Muse Dash", "PeroPeroGames", "Rhythm"),
        ("Nidhogg", "Messhof", "Action"),
        ("OMORI", "OMOCAT", "RPG"),
        ("PAYDAY 2", "Overkill Software", "Co-op Heist Shooter"),
        ("Palworld", "Pocketpair", "Survival Crafting"),
        ("P의 거짓", "NEOWIZ", "Action RPG (Soulslike)"),
        ("RUNNING WITH RIFLES", "Osumia Games", "Tactical Shooter"),
        ("Ready Action", "Various", "Action"),
        ("Red Dead Redemption 2", "Rockstar Games", "Open World Western Adventure"),
        ("Refind Self: 성격 진단 게임", "Various", "Adventure"),
        ("Rust", "Facepunch Studios", "Survival"),
        ("SEKIRO: SHADOWS DIE TWICE", "FromSoftware", "Action Adventure"),
        ("Sid Meier's Civilization V", "Firaxis Games", "4X Strategy"),
        ("Slay the Spire 2", "MegaCrit", "Roguelike Deck-builder"),
        ("Snow Bros. 2: With New Elves", "Toaplan", "Platformer Arcade"),
        ("Spiral Knights", "Grey Havens", "Action RPG"),
        ("Terraria", "Re-Logic", "Sandbox Survival"),
        ("The Forest", "Endnight Games", "Survival Horror"),
        ("The Sims 4 Get to Work", "Maxis", "Life Simulation"),
        ("This War of Mine", "11 bit studios", "Survival"),
        ("Unsouled", "Me we", "Action RPG"),
        ("Untitled Goose Game", "House House", "Puzzle"),
        ("V Rising", "Stunlock Studios", "Action Survival"),
        ("가정교사 히트맨 REBORN! DS 플레임 럼블 XX 초결전! 리얼 6조화", "Takara Tomy", "Fighting"),
        ("귀곡팔황", "Various", "Open World RPG"),
        ("기적의 분식집", "TalesShop", "Visual Novel"),
        ("나루토 최강닌자 대결집 DS", "Tomy", "Action"),
        ("놀러오세요 동물의 숲", "Nintendo", "Life Simulation"),
        ("뉴 슈퍼 마리오브라더스", "Nintendo", "Platformer"),
        ("닌자베이스볼배트맨", "Irem", "Beat 'em up"),
        ("대역전재판 -나루호도 류노스케의 모험-", "Capcom", "Visual Novel"),
        ("대역전재판2 -나루호도 류노스케의 각오-", "Capcom", "Visual Novel"),
        ("더 킹 오브 파이터즈 XV", "SNK", "Fighting"),
        ("도와줘! 리듬 히어로", "Nintendo", "Rhythm"),
        ("동방비상천 ~ Scarlet Weather Rhapsody.", "Twilight Frontier", "Fighting"),
        ("동방비상천칙 ~ 초대형 기뇰의 수수께끼를 쫓아서", "Twilight Frontier", "Fighting"),
        ("동방영야초 ~ Imperishable Night.", "Team Shanghai Alice", "Bullet Hell"),
        ("동방요요몽 ~ Perfect Cherry Blossom.", "Team Shanghai Alice", "Bullet Hell"),
        ("동방췌몽상 ~ Immaterial and Missing Power.", "Twilight Frontier", "Fighting"),
        ("동방홍룡동 ~ Unconnected Marketeers.", "Team Shanghai Alice", "Bullet Hell"),
        ("동방홍마향 ~ the Embodiment of Scarlet Devil.", "Team Shanghai Alice", "Bullet Hell"),
        ("드래곤 퀘스트 V 천공의 신부", "Square Enix", "RPG"),
        ("디지몬 챔피언십", "Bandai Namco", "Simulation"),
        ("라그나로크 DS", "GungHo", "RPG"),
        ("라이덴 2", "Seibu Kaihatsu", "Shooting"),
        ("라이프 이즈 퓨달: MMO", "Bitbox Ltd.", "MMORPG"),
        ("레이튼 교수와 이상한 마을", "Level-5", "Puzzle Adventure"),
        ("렐름 오브 더 매드 갓", "Deca Games", "Bullet Hell MMO"),
        ("록맨 X", "Capcom", "Action Platformer"),
        ("리듬 세상", "Nintendo", "Rhythm"),
        ("말랑말랑 두뇌교실", "Nintendo", "Puzzle"),
        ("메이드 인 와리오", "Nintendo", "Action"),
        ("메타포: 리판타지오", "Atlus", "RPG"),
        ("메탈슬러그", "SNK", "Run and Gun"),
        ("메탈슬러그 2", "SNK", "Run and Gun"),
        ("메탈슬러그 3", "SNK", "Run and Gun"),
        ("메탈슬러그 4", "SNK", "Run and Gun"),
        ("메탈슬러그 7", "SNK", "Run and Gun"),
        ("몬스터 헌터: 월드", "Capcom", "Action RPG"),
        ("미라클 어드벤처", "Data East", "Action"),
        ("별의 커비 도팡 일당의 습격", "Nintendo", "Platformer"),
        ("별의 커비 울트라 슈퍼 디럭스", "Nintendo", "Platformer"),
        ("삼국지 11", "Koei Tecmo", "Strategy"),
        ("삼국지 12", "Koei Tecmo", "Strategy"),
        ("삼국지 13", "Koei Tecmo", "Strategy"),
        ("삼국지 14", "Koei Tecmo", "Strategy"),
        ("삼국지 7", "Koei Tecmo", "Strategy"),
        ("삼국지 8", "Koei Tecmo", "Strategy"),
        ("삼국지 8 리메이크", "Koei Tecmo", "Strategy"),
        ("세피리아", "Various", "RPG"),
        ("섹시 파로디우스", "Konami", "Shooting"),
        ("슈퍼 마리오 64", "Nintendo", "Platformer"),
        ("슈퍼 마리오 랜드 2 6개의 금화", "Nintendo", "Platformer"),
        ("슈퍼 마리오 오디세이", "Nintendo", "Platformer"),
        ("슈퍼 피카 랜드", "Various", "Action"),
        ("스크리블너츠 언마스크드", "5TH Cell", "Puzzle"),
        ("스포어", "Maxis", "Simulation"),
        ("스폰지밥의 아틀란티스", "Various", "Action"),
        ("시벌리: 미디벌 워페어", "Torn Banner Studios", "Action"),
        ("썸썸편의점", "TalesShop", "Visual Novel"),
        ("엘더스크롤 5: 스카이림", "Bethesda", "Open World RPG"),
        ("역전검사 1", "Capcom", "Visual Novel"),
        ("역전재판 1", "Capcom", "Visual Novel"),
        ("역전재판 2", "Capcom", "Visual Novel"),
        ("역전재판 3", "Capcom", "Visual Novel"),
        ("역전재판 4", "Capcom", "Visual Novel"),
        ("오리와 눈먼 숲", "Moon Studios", "Metroidvania"),
        ("오리와 도깨비불", "Moon Studios", "Metroidvania"),
        ("오비스 루프", "Various", "Action"),
        ("유희왕 월드 챔피언십", "Konami", "CCG"),
        ("점프 얼티밋 스타즈", "Nintendo", "Fighting"),
        ("젤다의 전설 1", "Nintendo", "Action Adventure"),
        ("젤다의 전설 몽환의 모래시계", "Nintendo", "Action Adventure"),
        ("젤다의 전설 브레스 오브 더 와일드", "Nintendo", "Action Adventure"),
        ("젤다의 전설 스카워드 소드", "Nintendo", "Action Adventure"),
        ("젤다의 전설 시간의 오카리나", "Nintendo", "Action Adventure"),
        ("젤다의 전설 이상한 모자", "Nintendo", "Action Adventure"),
        ("짱구는 못말려 DS 알쏭달쏭 크레용 대작전!", "Various", "Action"),
        ("철권 6", "Bandai Namco", "Fighting"),
        ("철권 7", "Bandai Namco", "Fighting"),
        ("초강전기 키카이오", "Capcom", "Fighting"),
        ("치타맨 1", "Active Enterprises", "Action"),
        ("클레르 옵스큐르: 원정대 33", "Sandfall Interactive", "RPG"),
        ("킹 오브 파이터즈 98", "SNK", "Fighting"),
        ("킹덤컴 2", "Warhorse Studios", "RPG"),
        ("터치! 봄버맨 랜드", "Hudson Soft", "Action"),
        ("팀파이트 매니저", "Team Samoyed", "Simulation"),
        ("펜티먼트", "Obsidian Entertainment", "Adventure"),
        ("포켓몬: 야돈의 집", "The Pokémon Company", "Casual"),
        ("포켓몬스터 Y", "Nintendo", "RPG"),
        ("포켓몬스터 금", "Nintendo", "RPG"),
        ("포켓몬스터 기라티나", "Nintendo", "RPG"),
        ("포켓몬스터 디아루가", "Nintendo", "RPG"),
        ("포켓몬스터 레드", "Nintendo", "RPG"),
        ("포켓몬스터 문", "Nintendo", "RPG"),
        ("포켓몬스터 소드", "Nintendo", "RPG"),
        ("포켓몬스터 스칼렛", "Nintendo", "RPG"),
        ("포켓몬스터 알파 사파이어", "Nintendo", "RPG"),
        ("포켓몬스터 에메랄드", "Nintendo", "RPG"),
        ("포켓몬스터 울트라문", "Nintendo", "RPG"),
        ("포켓몬스터 파랑구조대", "Nintendo", "RPG"),
        ("포켓몬스터 파이어레드", "Nintendo", "RPG"),
        ("포켓몬스터 피카츄", "Nintendo", "RPG"),
        ("포켓몬스터 하트골드", "Nintendo", "RPG"),
        ("포켓몬스터 화이트", "Nintendo", "RPG"),
        ("포켓몬스터 화이트 2", "Nintendo", "RPG"),
        ("푸른뇌정 건볼트", "Inti Creates", "Action Platformer")
    ]

    content = "import type { GameHistoryItem } from '../../types';\n\n"
    content += "export const CONSOLE_GAMES: GameHistoryItem[] = [\n"
    items = []
    for i, (title, company, genre) in enumerate(CONSOLE_GAMES_LIST):
        items.append(f'  {{ "id": "console-{i}", "category": "Console/Steam", "genre": "{genre}", "title": "{title}", "company": "{company}" }}')
    content += ",\n".join(items) + "\n];\n"
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Console Database Restored ({len(CONSOLE_GAMES_LIST)} items)")

if __name__ == "__main__":
    restore_console_full()
